### ISSUE TITLE
Node2Vec training

### ISSUE THREAD

**Issue by soumitra9** [elaheh61/cotrained_ensemble_cyberbullying#2]
Hi, I am unable to understand how exactly did you use node2Vec to generate embedding for the user classifier. Like what would be the input to the Node2Vec model. I know it would be a graph but a graph of what?

**Comment by elahehraisi** [comment]
Hi Soumitra,Thanks for contacting me. I used gensem for node2vec. The graph will be file consisting of edges. Each line is the edge, which is start an end node. Did I answer your question? Please do not hesitate to ask for more clarification. I also could send you the code I used for node2vec generation. Let me know if you need that.
Regrads,Elaheh
    On Sunday, August 2, 2020, 02:33:22 PM EDT, Soumitra Mehrotra <notifications@github.com> wrote:  
 
 


Hi, I am unable to understand how exactly did you use node2Vec to generate embedding for the user classifier. Like what would be the input to the Node2Vec model. I know it would be a graph but a graph of what?

**Comment by soumitra9** [comment]
Thank you for your response. Can we connect over email? I still have few doubts, I'd appreciate it if you can help me out. Please drop an email to sxm6256@psu.edu

Regards,
Soumitra

**Comment by elahehraisi** [comment]
sure, my email address is elaheh@vt.edu.
    On Sunday, August 2, 2020, 06:16:37 PM EDT, Soumitra Mehrotra <notifications@github.com> wrote:  
 
 


Thank you for your response. Can we connect over email? I still have few doubts, I'd appreciate it if you can help me out. Please drop an email to sxm6256@psu.edu

Regards,
Soumitra
